" Vim color file DomClear
" generated by VimTax http://www.vimtax.com

set background=dark
hi clear
if exists("syntax_on")
	syntax reset
endif
set t_Co=256
let colors_name = "DomClear"

hi Comment	    guifg=#595959    ctermfg=52    gui=bold    cterm=bold 
hi Constant	    guifg=#7cff3b    ctermfg=89    gui=none    cterm=none 
hi Cursor	    guibg=#f0e68c    ctermbg=255    guifg=#708090    ctermfg=242    gui=none    cterm=none 
hi CursorLine	    guifg=#ffffff    ctermfg=231    guibg=#404040    ctermbg=237    gui=none    cterm=none 
hi ColorColumn	    guifg=#ffffff    ctermfg=231    guibg=#cc4040    ctermbg=252    gui=none    cterm=none 
hi Directory	    guifg=#008b8b    ctermfg=33    gui=none    cterm=none 
hi Folded	    guibg=#555555    ctermbg=239    guifg=#b3b3b3    ctermfg=249    gui=none    cterm=none 
hi Function	    guifg=#52b4ff    ctermfg=239    gui=bold    cterm=bold 
hi Identifier	    guifg=#52b4ff    ctermfg=239    gui=bold    cterm=bold 
hi LineNr	    guifg=#6e6e6e    ctermfg=242    gui=none    cterm=none 
hi MatchParen	    guifg=#ccffcc    ctermfg=252    guibg=#008b8b    ctermbg=33    gui=none    cterm=none 
hi Normal	    guifg=#ffffff    ctermfg=231    guibg=#383838    ctermbg=237    gui=none    cterm=none 
hi NonText	    guibg=#444444    ctermbg=239    guifg=#81bed6    ctermfg=89    gui=none    cterm=none 
hi Number	    guifg=#ffa0a0    ctermfg=214    gui=none    cterm=none 
hi PreProc	    guifg=#6efaff    ctermfg=242    gui=none    cterm=none 
hi Statement	    guifg=#d66565    ctermfg=160    gui=none    cterm=none 
hi Special	    guifg=#fffefc    ctermfg=226    gui=none    cterm=none 
hi SpecialKey	    guifg=#9acd32    ctermfg=247    gui=none    cterm=none 
hi StatusLine	    guibg=#c2bfa5    ctermbg=07    guifg=#000000    ctermfg=231    gui=none    cterm=none 
hi StatusLineNC	    guibg=#c2bfa5     ctermbg=07    guifg=#7777777    ctermfg=231    gui=none    cterm=none 
hi String	    guifg=#ffd500    ctermfg=220    gui=none    cterm=none 
hi StorageClass	    guifg=#bdb76b    ctermfg=250    gui=none    cterm=none 
hi Title	    guifg=#cd5c5c    ctermfg=252    gui=bold    cterm=bold 
hi Todo	    guifg=#ff0000    ctermfg=196    gui=none    cterm=none 
hi Type	    guifg=#ff0000    ctermfg=196    gui=none    cterm=none 
hi Underlined	    guifg=#80a0ff    ctermfg=89    gui=underline    cterm=underline 
hi VertSplit	    guibg=#c2bfa5     ctermbg=07    guifg=#7777777    ctermfg=231    gui=none    cterm=none 
hi Visual	    guifg=#fff6a6    ctermfg=226    guibg=#6b8e23    ctermbg=242    gui=none    cterm=none 
